# Generated by Django 5.1.1 on 2024-09-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(default='', max_length=12)),
                ('email', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('zip_code', models.CharField(max_length=500)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
            ],
        ),
    ]
